---
title: "covidmap"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(leaflet)
library(magrittr)
library(dbplyr)

```

Created at 8/22/2020

Reads data from https://raw.githubusercontent.com/nytimes/covid-19-data/master/live/us-states.csv.
```{r, echo=FALSE}
    csv <- read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/live/us-states.csv")
    csv1 <- read.csv("https://raw.githubusercontent.com/pchen8090/DevelopingDataProducts-w2/master/stateGeoCode.csv")
    csv$state <- as.character(csv$state)
    csv <- csv %>% merge(x=csv,y=csv1,by.x="state",by.y="location",all.y=TRUE)
    csv <- csv[c("cases","lat","lng")]
    df <- csv[rep(row.names(csv), csv$cases/1000),]
```

## Covid daily cases map (*1000):  

```{r map, echo=FALSE, warning=FALSE, message=FALSE}
        df %>% leaflet() %>%
            addTiles() %>%
            addMarkers(
                clusterOptions = markerClusterOptions(showCoverageOnHover = FALSE,spiderfyOnMaxZoom=FALSE,zoomToBoundsOnClick = FALSE))

```
*Created map with clustered markers. Please zoom in/out using scroll wheel.